### PR TITLE
Modifications for 1.1.0 version

### PR DESCRIPTION
**Pull request by dudevictor**
Hello! Excellent plugin! I made some changes to make it more generic.

Options added:

* updateComponentOnChange: true
Description: If false, it will not update the content inside the component when the user pick an item;

* itemProperty: null
Description: Defines which property will be accessed to show the value. It is used when you pass an array of Objects to 'items' option;

* pickerItemClass: "picker-item"
Description: Defines the selector class of the picker item. Use this option along with the "pickerItem" in template option;

* itemValueSelector: "i"
Description: For default, it will consider to use an \<i\> element for displaying the value of pickerItem, but to be more generic, you may specifies other element like a 'span' element. Use this option along with the "pickerItem" in template option;

Bugs fixed:

* Fix issue that occurs when the value selected matches with more than one option in popover like '1' and '11';
* Fix problem when define a "pickerItem" template that does not have "picker-item" class;
* Fix implementation of method isEmptyObject

Aditional:

* Update README.md file
* Update index.html with new example

See it online [here](https://dudevictor.github.io/bootstrap-popover-picker/) and [here](https://github.com/dudevictor/bootstrap-popover-picker/blob/master/README.md)

### CODE REVIEW

**Comment by dudevictor** [comment]
With these modifications you can generate a 1.1.0 version, like [here](https://github.com/dudevictor/bootstrap-popover-picker/releases)

**Comment by mjolnic** [comment]
Hi Victor thanks a lot for the awesome contribution! I find all that very useful.
I added you as a collaborator of the project so you could also regularly contribute directly with the project and release new versions.

Could you release 1.1.0 (I don't have access to the markdown of your release), it would be nice, but before could you update the version in `package.json` and remove the `version` property of `bower.json` (which is not longer used because Bower is using now tag versioning).

Thanks!

**Comment by dudevictor** [comment]
Ok, @mjolnic ! I will try to implement some suggestions made by @jasondavis before release a new version.

**Comment by mjolnic** [comment]
That would be great. Thank you both

**Pull request merged**
